set_property PACKAGE_PIN C25 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN B24 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN B27 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]